"""Benchmark vectorizer/classifier combinations for restaurant sentiment.

Read-only analysis. Compares Bag-of-Words and TF-IDF against four classifiers
using stratified cross-validation plus a held-out test split, writes a report to
docs/EVALUATION.md, and prints the best configuration. `train.py` remains the
source of truth for the deployed model — this script only informs that choice.

Unlike the original notebook flow, each vectorizer is fit inside a Pipeline on the
training folds only, so the reported numbers carry no test-set vocabulary leakage.

Usage:
    python evaluate.py
"""

from pathlib import Path

import pandas as pd
from sklearn.base import clone
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split
from sklearn.naive_bayes import BernoulliNB, MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC

from inference import preprocess

RANDOM_STATE = 0
MAX_FEATURES = 1500
N_SPLITS = 5
TEST_SIZE = 0.20
MAX_MISCLASSIFIED = 15

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "Restaurant_Reviews.tsv"
REPORT_PATH = ROOT / "docs" / "EVALUATION.md"

VECTORIZERS = {
    "BoW": lambda: CountVectorizer(max_features=MAX_FEATURES),
    "TF-IDF": lambda: TfidfVectorizer(max_features=MAX_FEATURES),
}
CLASSIFIERS = {
    "MultinomialNB": lambda: MultinomialNB(),
    "BernoulliNB": lambda: BernoulliNB(),
    "LogisticRegression": lambda: LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
    "LinearSVC": lambda: LinearSVC(random_state=RANDOM_STATE),
}


def _label(value: int) -> str:
    return "Positive" if value == 1 else "Negative"


def evaluate() -> dict:
    dataset = pd.read_csv(DATA_PATH, delimiter="\t", quoting=3)
    reviews = dataset["Review"].tolist()
    corpus = [preprocess(review) for review in reviews]
    y = dataset.iloc[:, -1].values

    indices = list(range(len(corpus)))
    train_idx, test_idx = train_test_split(
        indices, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )
    x_train = [corpus[i] for i in train_idx]
    x_test = [corpus[i] for i in test_idx]
    y_train = [int(y[i]) for i in train_idx]
    y_test = [int(y[i]) for i in test_idx]

    splitter = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
    results = []
    fitted = {}

    for vec_name, make_vec in VECTORIZERS.items():
        for clf_name, make_clf in CLASSIFIERS.items():
            pipeline = Pipeline([("vec", make_vec()), ("clf", make_clf())])

            cv_f1 = cross_val_score(
                clone(pipeline), x_train, y_train, cv=splitter, scoring="f1"
            ).mean()

            pipeline.fit(x_train, y_train)
            predictions = pipeline.predict(x_test)
            precision, recall, f1, _ = precision_recall_fscore_support(
                y_test, predictions, average="binary", zero_division=0
            )
            name = f"{vec_name} + {clf_name}"
            results.append(
                {
                    "name": name,
                    "cv_f1": cv_f1,
                    "accuracy": accuracy_score(y_test, predictions),
                    "precision": precision,
                    "recall": recall,
                    "f1": f1,
                }
            )
            fitted[name] = predictions

    results.sort(key=lambda row: row["cv_f1"], reverse=True)
    best = results[0]
    misclassified = [
        {
            "review": reviews[test_idx[i]],
            "actual": _label(y_test[i]),
            "predicted": _label(int(fitted[best["name"]][i])),
        }
        for i in range(len(y_test))
        if int(fitted[best["name"]][i]) != y_test[i]
    ]
    return {"results": results, "best": best, "misclassified": misclassified}


def render_report(report: dict) -> str:
    lines = [
        "# Model Evaluation",
        "",
        "Benchmark of vectorizer/classifier combinations, generated by `evaluate.py`.",
        "Each vectorizer is fit inside a Pipeline on the training folds only, so these",
        "numbers carry no test-set vocabulary leakage. Models are ranked by 5-fold",
        "stratified cross-validation F1 on the training split; the remaining columns are",
        f"measured on a {int(TEST_SIZE * 100)}% held-out test split "
        f"(`random_state={RANDOM_STATE}`).",
        "",
        "| Configuration | CV F1 | Test Acc | Precision | Recall | F1 |",
        "| ------------- | ----: | -------: | --------: | -----: | -: |",
    ]
    for row in report["results"]:
        lines.append(
            f"| {row['name']} | {row['cv_f1']:.3f} | {row['accuracy']:.3f} | "
            f"{row['precision']:.3f} | {row['recall']:.3f} | {row['f1']:.3f} |"
        )

    best = report["best"]
    lines += [
        "",
        f"**Best by CV F1: {best['name']}** "
        f"(test accuracy {best['accuracy']:.3f}, F1 {best['f1']:.3f}).",
        "",
        f"## Misclassified Reviews — {best['name']}",
        "",
        f"{len(report['misclassified'])} of the held-out reviews were misclassified. "
        f"A sample (up to {MAX_MISCLASSIFIED}):",
        "",
        "| Review | Actual | Predicted |",
        "| ------ | ------ | --------- |",
    ]
    for item in report["misclassified"][:MAX_MISCLASSIFIED]:
        review = item["review"].replace("|", "\\|").strip()
        if len(review) > 90:
            review = review[:87] + "..."
        lines.append(f"| {review} | {item['actual']} | {item['predicted']} |")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    report = evaluate()

    print(f"{'Configuration':<28} {'CV F1':>7} {'TestAcc':>8} {'F1':>7}")
    for row in report["results"]:
        print(f"{row['name']:<28} {row['cv_f1']:>7.3f} {row['accuracy']:>8.3f} {row['f1']:>7.3f}")
    print(f"\nBest by CV F1: {report['best']['name']}")

    REPORT_PATH.write_text(render_report(report), encoding="utf-8")
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
